[2024-04-13 16:28:02] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:07] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:12] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:17] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:22] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:27] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:27] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 0ff6e4ca1d612ede [::1]:32942 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:28:27] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 0ff6e4ca1d612ede [::1]:20130 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:28:32] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:37] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:42] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:47] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:52] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:57] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:28:59] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 0ff6e4ca1d612ede [::1]:44010 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:28:59] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 0ff6e4ca1d612ede [::1]:20130 failed checkpoint posthandshake: Connected to self
