[2024-04-13 15:46:02] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:46:02] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 0ff6e4ca1d612ede [::1]:49444 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:46:02] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 0ff6e4ca1d612ede [::1]:20130 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:46:07] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:46:12] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:46:17] [warning] orderServer.go:506 p3Chain/core/blockOrdering.(*BlockOrderServer).tryCommit [Block Ordering] Not enough signatures got in round version fbcd7606d33ced78799b005e8f86ec19db3288c2b76bd2d8f44639d8917bb8e2, height 1

[2024-04-13 15:46:17] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:46:22] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:46:27] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:46:32] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:46:34] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 0ff6e4ca1d612ede [::1]:39392 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:46:34] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 0ff6e4ca1d612ede [::1]:20130 failed checkpoint posthandshake: Connected to self
[2024-04-13 15:46:37] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:46:42] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:46:47] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:46:52] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 15:46:57] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
