[2024-04-13 19:07:00] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 19:07:05] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 19:07:07] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 21c561939067af2d [::1]:41060 failed checkpoint posthandshake: Connected to self
[2024-04-13 19:07:07] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 21c561939067af2d [::1]:20133 failed checkpoint posthandshake: Connected to self
[2024-04-13 19:07:10] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 19:07:15] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 19:07:20] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 19:07:25] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 19:07:30] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 19:07:35] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 19:07:40] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 21c561939067af2d [::1]:47632 failed checkpoint posthandshake: Connected to self
[2024-04-13 19:07:40] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 21c561939067af2d [::1]:20133 failed checkpoint posthandshake: Connected to self
[2024-04-13 19:07:40] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 19:07:45] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 19:07:50] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 19:07:55] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
