[2024-04-13 16:32:00] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:32:05] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:32:10] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:32:12] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 8b5bdccbc92a810e [::1]:58678 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:32:12] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 8b5bdccbc92a810e [::1]:20135 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:32:15] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:32:20] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:32:25] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:32:30] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:32:35] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:32:40] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:32:42] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 8b5bdccbc92a810e [::1]:41322 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:32:42] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 8b5bdccbc92a810e [::1]:20135 failed checkpoint posthandshake: Connected to self
[2024-04-13 16:32:45] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:32:50] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 16:32:55] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
