[2024-04-13 17:17:00] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:17:05] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:17:10] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:17:10] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 8b5bdccbc92a810e [::1]:20135 failed checkpoint posthandshake: Connected to self
[2024-04-13 17:17:10] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 8b5bdccbc92a810e [::1]:35374 failed checkpoint posthandshake: Connected to self
[2024-04-13 17:17:15] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:17:20] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:17:25] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:17:30] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:17:35] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:17:40] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:17:42] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 8b5bdccbc92a810e [::1]:51148 failed checkpoint posthandshake: Connected to self
[2024-04-13 17:17:42] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 8b5bdccbc92a810e [::1]:20135 failed checkpoint posthandshake: Connected to self
[2024-04-13 17:17:45] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:17:50] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-04-13 17:17:55] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
